name: 'Weaviate Issue Similarity Commenter'
description: 'Checks new GitHub issues for semantic similarity in Weaviate and comments if a match is found.'
inputs:
  issue_body:
    description: 'The body of the issue to check for similarity'
    required: true
  issue_number:
    description: 'The number of the issue to check for similarity'
    required: true
  weaviate_url:
    description: 'Weaviate instance URL'
    required: true
  weaviate_api_key:
    description: 'Weaviate API key'
    required: true
  github_token:
    description: 'GitHub token for posting comments'
    required: true
  collection_name:
    description: 'Weaviate collection name in which to search for similar issues'
    required: false
    default: 'GitHubIssues'
  github_repository:
    description: 'GitHub repository in which the issue was created, use the format "owner/repo". For example: "weaviate/weaviate"'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    WEAVIATE_URL: ${{ inputs.weaviate_url }}
    WEAVIATE_API_KEY: ${{ inputs.weaviate_api_key }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    ISSUE_BODY: ${{ inputs.issue_body }}
    ISSUE_NUMBER: ${{ inputs.issue_number }}
    GITHUB_REPO_NAME: ${{ inputs.github_repository }}
    COLLECTION_NAME: ${{ inputs.collection_name }}
branding:
  icon: 'search'
  color: 'blue' 